### PR TITLE
version up to upload maven repository

### PR DESCRIPTION
**Pull request by yohto**
### What is the necessity of this update? What is updated?
version up to upload maven repository

### How did you do the test? (Not required for updating documents)
uploaded to maven repository

### CODE REVIEW

**Comment by koijima** [comment]
LGTM

**Comment by koijima** [comment]
Merge is complete but there is a conflict.

> This branch has conflicts that must be resolved

I used this procedure as a guide, but there seems to be no difference.

-step 1
```
git checkout -b yohto-verup master
git pull https://github.com/yohto/yosegi.git verup
```

-step 2
```
git checkout master
git merge --no-ff yohto-verup
git push origin master
```

**Comment by koijima** [comment]
@yohto 
Check if the merge is complete, can you close it if there is no problem?

**Comment by yohto** [comment]
Thank you. I checked the conflict locally, but I couldn't find.
And, I used the command line to merge.

**Pull request closed without merging**
